name: Generate Folder Structure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-folder-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.email "timdesign1996@gmail.com"
          git config --global user.name "Ty Radman"

      - name: Make script executable
        run: chmod +x .github/workflows/generate_folder_structure.sh

      - name: Generate Folder Structure
        run: |
          .github/workflows/generate_folder_structure.sh

      - name: Commit and Push Changes
        run: |
          git add folder_structure.md
          git commit -m "Update folder structure"
          git push
